- name: Create frontend secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-secrets"
        namespace: "{{ k8s_namespace }}"
      type: Opaque
      stringData:
        AUTH_SECRET: "{{ secrets[env].frontend.secret }}"
        AUTH_TRUST_HOST: "true"
        NEXT_PUBLIC_SITE_URL: "https://audiohub.art"
        NEXTAUTH_URL: "https://audiohub.art"
